from __future__ import annotations

from .theme import PLAYBACK_SPEED_OPTIONS, VIDEO_INTERVAL_OPTIONS

SECTION_NAME = "Media Controls"
SPEED_OPTIONS = PLAYBACK_SPEED_OPTIONS
AI_INTERVAL_OPTIONS = VIDEO_INTERVAL_OPTIONS
